# Generated by Django 5.1.4 on 2024-12-07 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
